### PR TITLE
Refactor expression parsing. Fixes #15, implements #10.

### LINKED ISSUE #15: boolean operator precedence
The boolean operators `&&` and `||` don't appear to follow the common precedence rules. In particular the last one of these test fails:

```java
Map<String, Object> context = ImmutableMap.of("true", (Object) true, "false", false);

// tests that pass:
assertThat(render("{{ true && true }}", new MapBindings(context))).isEqualTo("true");
assertThat(render("{{ true || false }}", new MapBindings(context))).isEqualTo("true");
assertThat(render("{{ false || true }}", new MapBindings(context))).isEqualTo("true");
assertThat(render("{{ (false && false) || true }}", new MapBindings(context))).isEqualTo("true");

// failing test:
assertThat(render("{{ false && false || true }}", new MapBindings(context))).isEqualTo("true");
```

The common order of boolean operators is "and" before "or", see https://en.wikipedia.org/wiki/Logical_connective#Order_of_precedence

so `false && false || true` should be evaluated like `(false && false) || true` which is `true`.

### PR DESCRIPTION
**Pull request by dmfs**
Expressions are now parsed by a tree of `TermParser`s. Operation precedence is derived from the nesting level of the TermParser for the respective operation.

As a bonus, the `TermParser`s build shallow Term trees which, in most cases, have much less levels than before. This improves evaluation speed because values are evalued less often.

I didn't care about implementing any additional tests yet, just removed a few for methods which no longer exist. All other tests still pass without modification.

Note, Expression can probably be replaced with Term (maybe also rename Term back to Expression afterwards). I think this should be done with a separate ticket to keep the commit small.

### CODE REVIEW

**Comment by dmfs** [comment]
My idea was to implement field accessors as binary operators too. I.e.
```
value.key
value[key]
```
can be handled as binary operations with `value` being the left operand and `key` the right operand.

**Comment by dmfs** [comment]
Method calls would be ternary operators with the object, the method name and the list of parameters being the operands.
Not sure how to handle naked function calls like `function(a)`, is that supported after all?

**Comment by dmfs** [comment]
Also we could model `,` as a binary "iterable" operator. That would allow to model method parameters as a single iterable and also allow this syntax:
```
{% set a, b, c = b, c, a %}
```
With the right hand side evaluating to `iterable(b, iterable(c,a))`. The `IterableOperator` would have to  flatten nested iterables.

Anyway, that's just an idea.

**Review by codeka — APPROVED** [review]
I like where you're going here. I can see there's still a bit of work to do to clean up the Factor/ValueParser/Variable stuff, but I think this is going in the right direction. Thanks!

**Pull request merged**
